# Generated by Django 5.0.7 on 2024-07-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='utensil',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='utensil',
            old_name='name',
            new_name='nombre',
        ),
    ]
